// Static catalog data. Swap for an API response shape in src/services/courseService.js
// when a backend is connected — components consume the same fields either way.
//
// Categories mirror the Eduzyra By Althexus program poster:
// Software & Web Development, AI/Machine Learning & Generative AI, Data Science &
// Business Analytics, Cloud, DevOps & Cybersecurity, Design & Digital Marketing,
// Career, Communication & Professional Skills, and Mentorship, Certification & Business.
// New categories can be appended here as the catalog grows — no other file needs to change.

export const CATEGORIES = [
  'All',
  'Software & Web Development',
  'AI, Machine Learning & Generative AI',
  'Data Science & Business Analytics',
  'Cloud, DevOps & Cybersecurity',
  'Design & Digital Marketing',
  'Career, Communication & Professional Skills',
  'Mentorship, Certification & Business',
]

export const COURSES = [
  {
    id: 'full-stack-web-development',
    code: 'EDU-SWD-01',
    title: 'Full Stack Web Development',
    category: 'Software & Web Development',
    level: 'Beginner',
    instructor: 'Ramesh Pillai',
    duration: '90 Days',
    lessons: 41,
    rating: 4.8,
    students: 5004,
    price: 999,
    originalPrice: 2739,
    summary:
      'A practical, project-based path in full stack web development, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in full stack web development',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'web-development',
    code: 'EDU-SWD-02',
    title: 'Web Development',
    category: 'Software & Web Development',
    level: 'Intermediate',
    instructor: 'Deepika Nair',
    duration: '60 Days',
    lessons: 27,
    rating: 4.7,
    students: 3861,
    price: 999,
    originalPrice: 2659,
    summary:
      'A practical, project-based path in web development, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in web development',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'python-development',
    code: 'EDU-SWD-03',
    title: 'Python Development',
    category: 'Software & Web Development',
    level: 'Intermediate',
    instructor: 'Aditi Rao',
    duration: '60 Days',
    lessons: 27,
    rating: 4.5,
    students: 3775,
    price: 999,
    originalPrice: 2559,
    summary:
      'A practical, project-based path in python development, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in python development',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'python-full-stack-development',
    code: 'EDU-SWD-04',
    title: 'Python Full Stack Development',
    category: 'Software & Web Development',
    level: 'Beginner',
    instructor: 'Vikram Suresh',
    duration: '90 Days',
    lessons: 41,
    rating: 4.8,
    students: 1943,
    price: 999,
    originalPrice: 2669,
    summary:
      'A practical, project-based path in python full stack development, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in python full stack development',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'java-development',
    code: 'EDU-SWD-05',
    title: 'Java Development',
    category: 'Software & Web Development',
    level: 'Intermediate',
    instructor: 'Ramesh Pillai',
    duration: '60 Days',
    lessons: 27,
    rating: 4.9,
    students: 5168,
    price: 999,
    originalPrice: 2649,
    summary:
      'A practical, project-based path in java development, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in java development',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'java-full-stack-development',
    code: 'EDU-SWD-06',
    title: 'Java Full Stack Development',
    category: 'Software & Web Development',
    level: 'Beginner',
    instructor: 'Deepika Nair',
    duration: '90 Days',
    lessons: 41,
    rating: 4.6,
    students: 1048,
    price: 999,
    originalPrice: 2739,
    summary:
      'A practical, project-based path in java full stack development, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in java full stack development',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'backend-development-with-node-js',
    code: 'EDU-SWD-07',
    title: 'Backend Development with Node.js',
    category: 'Software & Web Development',
    level: 'Intermediate',
    instructor: 'Aditi Rao',
    duration: '60 Days',
    lessons: 27,
    rating: 4.8,
    students: 1183,
    price: 999,
    originalPrice: 2589,
    summary:
      'A practical, project-based path in backend development with node.js, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in backend development with node.js',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'php-development',
    code: 'EDU-SWD-08',
    title: 'PHP Development',
    category: 'Software & Web Development',
    level: 'Intermediate',
    instructor: 'Vikram Suresh',
    duration: '60 Days',
    lessons: 27,
    rating: 4.6,
    students: 2775,
    price: 999,
    originalPrice: 2459,
    summary:
      'A practical, project-based path in php development, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in php development',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'mobile-application-development',
    code: 'EDU-SWD-09',
    title: 'Mobile Application Development',
    category: 'Software & Web Development',
    level: 'Beginner',
    instructor: 'Ramesh Pillai',
    duration: '90 Days',
    lessons: 41,
    rating: 4.5,
    students: 3021,
    price: 999,
    originalPrice: 2599,
    summary:
      'A practical, project-based path in mobile application development, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in mobile application development',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'qa-software-testing',
    code: 'EDU-SWD-10',
    title: 'QA & Software Testing',
    category: 'Software & Web Development',
    level: 'Intermediate',
    instructor: 'Deepika Nair',
    duration: '60 Days',
    lessons: 27,
    rating: 4.7,
    students: 3924,
    price: 999,
    originalPrice: 2659,
    summary:
      'A practical, project-based path in qa & software testing, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in qa & software testing',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'software-engineering-git-github',
    code: 'EDU-SWD-11',
    title: 'Software Engineering & Git/GitHub',
    category: 'Software & Web Development',
    level: 'Beginner',
    instructor: 'Aditi Rao',
    duration: '30 Days',
    lessons: 14,
    rating: 4.9,
    students: 2682,
    price: 499,
    originalPrice: 1129,
    summary:
      'A practical, project-based path in software engineering & git/github, built for the software & web development track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in software engineering & git/github',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 3 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 3 },
      { title: 'Applied Projects', lessons: 3 },
      { title: 'Real-World Case Studies', lessons: 3 },
      { title: 'Capstone Project & Career Prep', lessons: 3 },
    ],
  },
  {
    id: 'ai-machine-learning',
    code: 'EDU-AIM-01',
    title: 'AI & Machine Learning',
    category: 'AI, Machine Learning & Generative AI',
    level: 'Beginner',
    instructor: 'Sanjana Iyer',
    duration: '90 Days',
    lessons: 41,
    rating: 4.9,
    students: 1295,
    price: 999,
    originalPrice: 2299,
    summary:
      'A practical, project-based path in ai & machine learning, built for the ai, machine learning & generative ai track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in ai & machine learning',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'generative-ai',
    code: 'EDU-AIM-02',
    title: 'Generative AI',
    category: 'AI, Machine Learning & Generative AI',
    level: 'Intermediate',
    instructor: 'Karthik Menon',
    duration: '60 Days',
    lessons: 27,
    rating: 4.8,
    students: 1764,
    price: 999,
    originalPrice: 2399,
    summary:
      'A practical, project-based path in generative ai, built for the ai, machine learning & generative ai track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in generative ai',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'machine-learning-foundations',
    code: 'EDU-AIM-03',
    title: 'Machine Learning Foundations',
    category: 'AI, Machine Learning & Generative AI',
    level: 'Intermediate',
    instructor: 'Sanjana Iyer',
    duration: '60 Days',
    lessons: 27,
    rating: 4.9,
    students: 1288,
    price: 999,
    originalPrice: 2209,
    summary:
      'A practical, project-based path in machine learning foundations, built for the ai, machine learning & generative ai track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in machine learning foundations',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'prompt-engineering-ai-automation',
    code: 'EDU-AIM-04',
    title: 'Prompt Engineering & AI Automation',
    category: 'AI, Machine Learning & Generative AI',
    level: 'Beginner',
    instructor: 'Karthik Menon',
    duration: '45 Days',
    lessons: 20,
    rating: 4.9,
    students: 1868,
    price: 799,
    originalPrice: 2079,
    summary:
      'A practical, project-based path in prompt engineering & ai automation, built for the ai, machine learning & generative ai track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in prompt engineering & ai automation',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 4 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 4 },
      { title: 'Applied Projects', lessons: 4 },
      { title: 'Real-World Case Studies', lessons: 4 },
      { title: 'Capstone Project & Career Prep', lessons: 4 },
    ],
  },
  {
    id: 'ai-tools-productivity',
    code: 'EDU-AIM-05',
    title: 'AI Tools & Productivity',
    category: 'AI, Machine Learning & Generative AI',
    level: 'Beginner',
    instructor: 'Sanjana Iyer',
    duration: '30 Days',
    lessons: 14,
    rating: 4.5,
    students: 704,
    price: 499,
    originalPrice: 1289,
    summary:
      'A practical, project-based path in ai tools & productivity, built for the ai, machine learning & generative ai track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in ai tools & productivity',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 3 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 3 },
      { title: 'Applied Projects', lessons: 3 },
      { title: 'Real-World Case Studies', lessons: 3 },
      { title: 'Capstone Project & Career Prep', lessons: 3 },
    ],
  },
  {
    id: 'data-science-analytics',
    code: 'EDU-DSB-01',
    title: 'Data Science & Analytics',
    category: 'Data Science & Business Analytics',
    level: 'Beginner',
    instructor: 'Priya Nambiar',
    duration: '90 Days',
    lessons: 41,
    rating: 4.8,
    students: 4596,
    price: 999,
    originalPrice: 2449,
    summary:
      'A practical, project-based path in data science & analytics, built for the data science & business analytics track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in data science & analytics',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'data-analytics-with-python',
    code: 'EDU-DSB-02',
    title: 'Data Analytics with Python',
    category: 'Data Science & Business Analytics',
    level: 'Intermediate',
    instructor: 'Karthik Menon',
    duration: '60 Days',
    lessons: 27,
    rating: 4.7,
    students: 1142,
    price: 999,
    originalPrice: 2419,
    summary:
      'A practical, project-based path in data analytics with python, built for the data science & business analytics track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in data analytics with python',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'power-bi-business-intelligence',
    code: 'EDU-DSB-03',
    title: 'Power BI & Business Intelligence',
    category: 'Data Science & Business Analytics',
    level: 'Beginner',
    instructor: 'Priya Nambiar',
    duration: '45 Days',
    lessons: 20,
    rating: 4.7,
    students: 1944,
    price: 799,
    originalPrice: 2209,
    summary:
      'A practical, project-based path in power bi & business intelligence, built for the data science & business analytics track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in power bi & business intelligence',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 4 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 4 },
      { title: 'Applied Projects', lessons: 4 },
      { title: 'Real-World Case Studies', lessons: 4 },
      { title: 'Capstone Project & Career Prep', lessons: 4 },
    ],
  },
  {
    id: 'advanced-excel-business-analytics',
    code: 'EDU-DSB-04',
    title: 'Advanced Excel & Business Analytics',
    category: 'Data Science & Business Analytics',
    level: 'Beginner',
    instructor: 'Karthik Menon',
    duration: '30 Days',
    lessons: 14,
    rating: 4.7,
    students: 4202,
    price: 499,
    originalPrice: 1259,
    summary:
      'A practical, project-based path in advanced excel & business analytics, built for the data science & business analytics track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in advanced excel & business analytics',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 3 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 3 },
      { title: 'Applied Projects', lessons: 3 },
      { title: 'Real-World Case Studies', lessons: 3 },
      { title: 'Capstone Project & Career Prep', lessons: 3 },
    ],
  },
  {
    id: 'aws-cloud-computing',
    code: 'EDU-CDC-01',
    title: 'AWS Cloud Computing',
    category: 'Cloud, DevOps & Cybersecurity',
    level: 'Intermediate',
    instructor: 'Farhan Sheikh',
    duration: '60 Days',
    lessons: 27,
    rating: 4.8,
    students: 5116,
    price: 999,
    originalPrice: 2539,
    summary:
      'A practical, project-based path in aws cloud computing, built for the cloud, devops & cybersecurity track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in aws cloud computing',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'cloud-computing-foundations',
    code: 'EDU-CDC-02',
    title: 'Cloud Computing Foundations',
    category: 'Cloud, DevOps & Cybersecurity',
    level: 'Beginner',
    instructor: 'Neha Kulkarni',
    duration: '45 Days',
    lessons: 20,
    rating: 4.8,
    students: 1884,
    price: 799,
    originalPrice: 1979,
    summary:
      'A practical, project-based path in cloud computing foundations, built for the cloud, devops & cybersecurity track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in cloud computing foundations',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 4 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 4 },
      { title: 'Applied Projects', lessons: 4 },
      { title: 'Real-World Case Studies', lessons: 4 },
      { title: 'Capstone Project & Career Prep', lessons: 4 },
    ],
  },
  {
    id: 'devops-ci-cd-foundations',
    code: 'EDU-CDC-03',
    title: 'DevOps & CI/CD Foundations',
    category: 'Cloud, DevOps & Cybersecurity',
    level: 'Intermediate',
    instructor: 'Farhan Sheikh',
    duration: '60 Days',
    lessons: 27,
    rating: 4.7,
    students: 1309,
    price: 999,
    originalPrice: 2579,
    summary:
      'A practical, project-based path in devops & ci/cd foundations, built for the cloud, devops & cybersecurity track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in devops & ci/cd foundations',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'cloud-devops-foundations',
    code: 'EDU-CDC-04',
    title: 'Cloud & DevOps Foundations',
    category: 'Cloud, DevOps & Cybersecurity',
    level: 'Intermediate',
    instructor: 'Neha Kulkarni',
    duration: '60 Days',
    lessons: 27,
    rating: 4.5,
    students: 589,
    price: 999,
    originalPrice: 2499,
    summary:
      'A practical, project-based path in cloud & devops foundations, built for the cloud, devops & cybersecurity track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in cloud & devops foundations',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'cybersecurity-soc-analyst',
    code: 'EDU-CDC-05',
    title: 'Cybersecurity & SOC Analyst',
    category: 'Cloud, DevOps & Cybersecurity',
    level: 'Beginner',
    instructor: 'Farhan Sheikh',
    duration: '90 Days',
    lessons: 41,
    rating: 4.7,
    students: 1724,
    price: 999,
    originalPrice: 2479,
    summary:
      'A practical, project-based path in cybersecurity & soc analyst, built for the cloud, devops & cybersecurity track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in cybersecurity & soc analyst',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'ethical-hacking-cybersecurity',
    code: 'EDU-CDC-06',
    title: 'Ethical Hacking & Cybersecurity',
    category: 'Cloud, DevOps & Cybersecurity',
    level: 'Beginner',
    instructor: 'Neha Kulkarni',
    duration: '90 Days',
    lessons: 41,
    rating: 4.5,
    students: 1916,
    price: 999,
    originalPrice: 2779,
    summary:
      'A practical, project-based path in ethical hacking & cybersecurity, built for the cloud, devops & cybersecurity track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in ethical hacking & cybersecurity',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'ui-ux-design',
    code: 'EDU-DDM-01',
    title: 'UI/UX Design',
    category: 'Design & Digital Marketing',
    level: 'Intermediate',
    instructor: 'Arjun Verma',
    duration: '60 Days',
    lessons: 27,
    rating: 4.7,
    students: 3163,
    price: 999,
    originalPrice: 2439,
    summary:
      'A practical, project-based path in ui/ux design, built for the design & digital marketing track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in ui/ux design',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'graphic-design-visual-communication',
    code: 'EDU-DDM-02',
    title: 'Graphic Design & Visual Communication',
    category: 'Design & Digital Marketing',
    level: 'Intermediate',
    instructor: 'Ritu Chawla',
    duration: '60 Days',
    lessons: 27,
    rating: 4.5,
    students: 2665,
    price: 999,
    originalPrice: 2309,
    summary:
      'A practical, project-based path in graphic design & visual communication, built for the design & digital marketing track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in graphic design & visual communication',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'digital-marketing-growth',
    code: 'EDU-DDM-03',
    title: 'Digital Marketing & Growth',
    category: 'Design & Digital Marketing',
    level: 'Intermediate',
    instructor: 'Arjun Verma',
    duration: '60 Days',
    lessons: 27,
    rating: 4.6,
    students: 2423,
    price: 999,
    originalPrice: 2659,
    summary:
      'A practical, project-based path in digital marketing & growth, built for the design & digital marketing track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in digital marketing & growth',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 6 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 6 },
      { title: 'Applied Projects', lessons: 5 },
      { title: 'Real-World Case Studies', lessons: 5 },
      { title: 'Capstone Project & Career Prep', lessons: 5 },
    ],
  },
  {
    id: 'seo-search-marketing',
    code: 'EDU-DDM-04',
    title: 'SEO & Search Marketing',
    category: 'Design & Digital Marketing',
    level: 'Beginner',
    instructor: 'Ritu Chawla',
    duration: '45 Days',
    lessons: 20,
    rating: 4.7,
    students: 4436,
    price: 799,
    originalPrice: 2009,
    summary:
      'A practical, project-based path in seo & search marketing, built for the design & digital marketing track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in seo & search marketing',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 4 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 4 },
      { title: 'Applied Projects', lessons: 4 },
      { title: 'Real-World Case Studies', lessons: 4 },
      { title: 'Capstone Project & Career Prep', lessons: 4 },
    ],
  },
  {
    id: 'professional-english-communication-skills',
    code: 'EDU-CCP-01',
    title: 'Professional English & Communication Skills',
    category: 'Career, Communication & Professional Skills',
    level: 'Beginner',
    instructor: 'Arjun Verma',
    duration: '45 Days',
    lessons: 20,
    rating: 4.5,
    students: 1105,
    price: 599,
    originalPrice: 1639,
    summary:
      'A practical, project-based path in professional english & communication skills, built for the career, communication & professional skills track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in professional english & communication skills',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 4 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 4 },
      { title: 'Applied Projects', lessons: 4 },
      { title: 'Real-World Case Studies', lessons: 4 },
      { title: 'Capstone Project & Career Prep', lessons: 4 },
    ],
  },
  {
    id: 'interview-career-readiness',
    code: 'EDU-CCP-02',
    title: 'Interview & Career Readiness',
    category: 'Career, Communication & Professional Skills',
    level: 'Beginner',
    instructor: 'Meera Joshi',
    duration: '30 Days',
    lessons: 14,
    rating: 4.7,
    students: 4030,
    price: 499,
    originalPrice: 1189,
    summary:
      'A practical, project-based path in interview & career readiness, built for the career, communication & professional skills track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in interview & career readiness',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 3 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 3 },
      { title: 'Applied Projects', lessons: 3 },
      { title: 'Real-World Case Studies', lessons: 3 },
      { title: 'Capstone Project & Career Prep', lessons: 3 },
    ],
  },
  {
    id: 'freelancing-remote-work-skills',
    code: 'EDU-CCP-03',
    title: 'Freelancing & Remote Work Skills',
    category: 'Career, Communication & Professional Skills',
    level: 'Beginner',
    instructor: 'Arjun Verma',
    duration: '30 Days',
    lessons: 14,
    rating: 4.6,
    students: 809,
    price: 499,
    originalPrice: 1139,
    summary:
      'A practical, project-based path in freelancing & remote work skills, built for the career, communication & professional skills track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in freelancing & remote work skills',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 3 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 3 },
      { title: 'Applied Projects', lessons: 3 },
      { title: 'Real-World Case Studies', lessons: 3 },
      { title: 'Capstone Project & Career Prep', lessons: 3 },
    ],
  },
  {
    id: 'typing-computer-productivity',
    code: 'EDU-CCP-04',
    title: 'Typing & Computer Productivity',
    category: 'Career, Communication & Professional Skills',
    level: 'Beginner',
    instructor: 'Meera Joshi',
    duration: '30 Days',
    lessons: 14,
    rating: 4.7,
    students: 3045,
    price: 499,
    originalPrice: 1349,
    summary:
      'A practical, project-based path in typing & computer productivity, built for the career, communication & professional skills track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in typing & computer productivity',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 3 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 3 },
      { title: 'Applied Projects', lessons: 3 },
      { title: 'Real-World Case Studies', lessons: 3 },
      { title: 'Capstone Project & Career Prep', lessons: 3 },
    ],
  },
  {
    id: 'neet-mentorship-program',
    code: 'EDU-MCB-01',
    title: 'NEET Mentorship Program',
    category: 'Mentorship, Certification & Business',
    level: 'Beginner',
    instructor: 'Meera Joshi',
    duration: '90 Days',
    lessons: 41,
    rating: 4.9,
    students: 3136,
    price: 999,
    originalPrice: 2689,
    summary:
      'A practical, project-based path in neet mentorship program, built for the mentorship, certification & business track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in neet mentorship program',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 9 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 8 },
      { title: 'Applied Projects', lessons: 8 },
      { title: 'Real-World Case Studies', lessons: 8 },
      { title: 'Capstone Project & Career Prep', lessons: 8 },
    ],
  },
  {
    id: 'skill-assessment-certification',
    code: 'EDU-MCB-02',
    title: 'Skill Assessment & Certification',
    category: 'Mentorship, Certification & Business',
    level: 'Beginner',
    instructor: 'Dr. Sameer Gupta',
    duration: '1 - 7 Days',
    lessons: 6,
    rating: 4.7,
    students: 4357,
    price: 299,
    originalPrice: 999,
    summary:
      'A practical, project-based path in skill assessment & certification, built for the mentorship, certification & business track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in skill assessment & certification',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 3 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 3 },
      { title: 'Applied Projects', lessons: 3 },
      { title: 'Real-World Case Studies', lessons: 3 },
      { title: 'Capstone Project & Career Prep', lessons: 3 },
    ],
  },
  {
    id: 'business-development-sales-fundamentals',
    code: 'EDU-MCB-03',
    title: 'Business Development & Sales Fundamentals',
    category: 'Mentorship, Certification & Business',
    level: 'Beginner',
    instructor: 'Meera Joshi',
    duration: '45 Days',
    lessons: 20,
    rating: 4.6,
    students: 3540,
    price: 799,
    originalPrice: 2029,
    summary:
      'A practical, project-based path in business development & sales fundamentals, built for the mentorship, certification & business track with live mentorship and career support.',
    outcomes: [
      'Build real, portfolio-ready projects in business development & sales fundamentals',
      'Get hands-on mentorship and structured live training',
      'Earn a certification and career support on completion',
    ],
    syllabus: [
      { title: 'Foundations & Setup', lessons: 4 },
      { title: 'Core Concepts & Hands-on Practice', lessons: 4 },
      { title: 'Applied Projects', lessons: 4 },
      { title: 'Real-World Case Studies', lessons: 4 },
      { title: 'Capstone Project & Career Prep', lessons: 4 },
    ],
  },
]

export function getCourseById(id) {
  return COURSES.find((course) => course.id === id)
}

